export const PROJECTS_FAILED = 'PROJECTS_FAILED';
export const ADD_PROJECTS = 'ADD_PROJECTS';

export const ADD_PROJECT = 'ADD_PROJECT';
export const PROJECT_FAILED = 'PROJECT_FAILED';

export const ADD_TASK = 'ADD_TASK';
export const TASK_FAILED = 'TASK_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const COMMENT_FAILED = 'COMMENT_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const USERS_FAILED = 'USERS_FAILED';
export const ADD_USERS = 'ADD_USERS';
